[package]
name = "ch2-account-balance"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
ractor = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }

local-logging = { workspace = true }
